package views.budget.modify;
import utils.CuttingService;
import views.IToggleableView;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.event.ItemListener;
import java.util.ArrayList;
import java.util.List;

public interface IBudgetModifyView extends IToggleableView {
    JTextField getWidthMeasureTextField();
    JTextField getHeightMeasureTextField();
    int getPreviewTableSelectedRow();
    String getBudgetClientName();
    String getBudgetDate();
    void clearPreviewTable();
    void clearClientTable();
    void clearProductTable();
    JComboBox<String> getCategoriesComboBox();
    void comboBoxListenerSet(ItemListener listener);
    void setProductStringTableValueAt(int row, int col, String value);
    void setCitiesComboBox(ArrayList<String> cities);
    JComboBox<String> getCitiesComboBox();
    void setClientStringTableValueAt(int row, int col, String value);
    void setClientIntTableValueAt(int row, int col, int value);
    int getClientTableSelectedRow();
    JTable getPreviewTable();
    String getProductStringTableValueAt(int row, int col);
    void setPreviewStringTableValueAt(int row, int col, String value);
    String getPreviewStringTableValueAt(int row, int col);
    int getProductTableSelectedRow();
    JTextField getProductsTextField();
    JTextField getAmountTextField();
    JTextField getObservationsTextField();
    DefaultTableModel getPreviewTableModel();
    JTextArea getPriceTextArea();
    StringBuilder getStringBuilder();
    JTable getProductsResultTable();
    void setInitialPanelsVisibility();
    void setSecondPanelsVisibility();
    JCheckBox getClientSelectedCheckBox();
    void setTableVisibility(JTable table);
    void restartWindow();
    DefaultTableModel getClientResultTableModel();
    int getFilledRowsCount(JTable table);
    JFrame getWindowFrame();
    void addCuttingService(CuttingService cuttingService);
}
