package views.budget;
import presenters.budget.BudgetCreatePresenter;
import utils.CuttingService;
import views.IToggleableView;
import utils.Product;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.event.ItemListener;
import java.util.ArrayList;
import java.util.List;

public interface IBudgetCreateView extends IToggleableView {
    String getBudgetClientName();
    String getBudgetDate();
    void clearPreviewTable();
    void clearClientTable();
    void clearProductTable();
    JComboBox<String> getCategoriesComboBox();
    void comboBoxListenerSet(ItemListener listener);
    void setProductStringTableValueAt(int row, int col, String value);
    void addProductToPreviewTable(Product product, int row);
    void setCitiesComboBox(ArrayList<String> cities);
    JComboBox<String> getCitiesComboBox();
    void setClientStringTableValueAt(int row, int col, String value);
    void setClientIntTableValueAt(int row, int col, int value);
    void setClientDoubleTableValueAt(int row, int col, Double value);
    int getClientTableSelectedRow();
    JTable getPreviewTable();
    String getProductStringTableValueAt(int row, int col);
    void setPreviewStringTableValueAt(int row, int col, String value);
    String getPreviewStringTableValueAt(int row, int col);
    int getProductTableSelectedRow();
    JTextField getProductsTextField();
    JTextField getAmountTextField();
    JTextField getWidthMeasureTextField();
    JTextField getHeightMeasureTextField();
    JTextField getObservationsTextField();
    DefaultTableModel getPreviewTableModel();
    JTextArea getPriceTextArea();
    void setTableVisibility(JTable table);
    JCheckBox getClientSelectedCheckBox();
    void setInitialPanelsVisibility();
    void setSecondPanelsVisibility();
    JTable getProductsResultTable();
    DefaultTableModel getClientResultTableModel();
    StringBuilder getStringBuilder();
    JFrame getWindowFrame();
    List<String[]> getPreviewTableFilledRowsData();
    void restartWindow();
    void addCuttingService(CuttingService cuttingService);
}
